version: '3.7'

services:

  postgres:
    container_name: shortener_postgres
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: shortener
      POSTGRES_PASSWORD: shortener
